[package]
name = "graph_of_charracters"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
id-set = "0.2.2"
serde = { version = "1.0", features = ["derive"] }
serde_yaml = "0.9"
